version: "3.9"

services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
            - CLIENT_PORT=${CLIENT_PORT}
            - SERVER_PORT=${SERVER_PORT}
        networks:
          - awesome

    server:
        container_name: prakticum-server
        image: prackicum-server
        env_file:
            - .env.sample
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            SERVER_PORT: ${SERVER_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_PORT}
            DOCKER_ENVIRONMENT: 1
        depends_on:
            - postgres
        networks:
            - awesome

    postgres:
        container_name: postgres
        image: postgres:15
        restart: unless-stopped
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            # POSTGRES_INITDB_ARGS: "--listen_addresses=*"
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        networks:
            - awesome

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.15
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
            PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
            PGADMIN_SETUP_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_SETUP_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
        ports:
            - "${PGADMIN_MAIN_PORT}:${PGADMIN_LISTEN_PORT}"
        volumes:
            - ./tmp/pgadmin-data:/var/lib/pgadmin/data
        depends_on:
            - postgres
        platform: linux/amd64 # Закоментить для windows
        networks:
            - awesome

volumes:
    pgdata:
        external: false
    pgadmin-data:
        external: false

networks:
    awesome:
      driver: bridge
